// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParksApi.Data;

#nullable disable

namespace NationalParksApi.Migrations
{
    [DbContext(typeof(ParkDbContext))]
    [Migration("20230707161015_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParksApi.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activities")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activities = "Hiking, Wildlife Viewing, Camping",
                            Description = "First national park in the world.",
                            ParkName = "Yellowstone",
                            State = "Wyoming"
                        },
                        new
                        {
                            Id = 2,
                            Activities = "Hiking, Rock Climbing, Camping",
                            Description = "Famous for its waterfalls.",
                            ParkName = "Yosemite",
                            State = "California"
                        },
                        new
                        {
                            Id = 3,
                            Activities = "Hiking, Rafting, Helicopter Tours",
                            Description = "Known for its visually overwhelming size.",
                            ParkName = "Grand Canyon",
                            State = "Arizona"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
